repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "/usr/bin/bash ./.run-mypy "
        language: system
        types: [python]
        require_serial: true
        verbose: true
